spring:
  application:
    name: aws-s3
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

aws:
  s3:
    bucket-name: filthi-bucket # root container -> must be unique
    region: ap-southeast-2       # location of the servers -> must be where most users are located
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
